name:                advent2017
version:             0.1.0.0
github:              githubuser/advent2017
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/advent2017#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- linear
- containers
- unordered-containers
- array
- monad-loops
- text
- vector
- mtl
- split

library:
  source-dirs: src

executables:
  advent2017-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent2017

tests:
  advent2017-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent2017
